In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [94]:
from proj1_helpers import *
from implementations import *

DATA_TRAIN_PATH = '../data/train.csv.zip'
DATA_TEST_PATH = '../data/test.csv.zip'

# Load data
data_train = pd.read_csv(DATA_TRAIN_PATH)
data_test = pd.read_csv(DATA_TEST_PATH) # NOTE: This is test for SUBMISSION, not test for training.

# Make Y binary [-1,1]
data_train.loc[data_train['Prediction'] == 's','Prediction'] = 1
data_train.loc[data_train['Prediction'] == 'b','Prediction'] = 0
data_train['Prediction'] = pd.to_numeric(data_train['Prediction'])

# Extract y
y_train = data_train['Prediction'].to_frame()
y = y_train.to_numpy()

# Get ids
id_train = data_train['Id'].to_frame()

# Get x
x_train = data_train.copy()
x_train.drop(['Id','Prediction'], 1, inplace=True) 
x = x_train.to_numpy()


## Hackz

In [92]:
# Initial survey of data
from scipy import stats
import statsmodels.api as sm
import statsmodels.formula.api as smf

mod = smf.logit(formula='Prediction ~  DER_mass_MMC + DER_mass_transverse_met_lep + DER_mass_vis + \
                         DER_pt_h + DER_deltaeta_jet_jet + DER_mass_jet_jet + \
                         DER_pt_ratio_lep_tau + DER_met_phi_centrality + DER_lep_eta_centrality + \
                         PRI_tau_pt + PRI_tau_eta + PRI_tau_phi + PRI_lep_pt + PRI_lep_eta + PRI_lep_phi + \
                         PRI_met + PRI_met_phi + PRI_met_sumet + PRI_jet_num + PRI_jet_leading_pt + \
                         PRI_jet_leading_eta + PRI_jet_leading_phi + PRI_jet_subleading_pt + \
                         PRI_jet_subleading_eta + PRI_jet_subleading_phi + PRI_jet_all_pt', data=data_train)
res = mod.fit()
print(res.summary())


Optimization terminated successfully.
         Current function value: 0.513424
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:             Prediction   No. Observations:               250000
Model:                          Logit   Df Residuals:                   249973
Method:                           MLE   Df Model:                           26
Date:                Fri, 22 Oct 2021   Pseudo R-squ.:                  0.2013
Time:                        15:54:38   Log-Likelihood:            -1.2836e+05
converged:                       True   LL-Null:                   -1.6070e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                       1.1989      0.079     15.163      0.000   

## Using above
Above can be used to test different models for logistic regression. Test different combinations etc, also get parameters (coefficients). We can begin by only using the predictors with strong coefficients, for example "DER_pt_ratio_lep_tau". /Martin

## Do your thing crazy machine learning thing here :) ...

In [102]:
# Extend data
tx = build_poly_1D(x, 1)

# fix this: Not working atm
x_train,y_train,x_test,y_test = split_data(tx, y, 0.8, seed=1)

# initialize a model (Not tested yet)
initial_w = initialize a model
max_iters = ?
gamma = ?

# Use cross validation?

# Logistical Regression (Not tested yet)
w, loss = logistic_regression(y, tx, initial_w, max_iters, gamma)

# Test model! (Not tested yet)
y_pred = predict_labels(w, x_test)



[[   1.     138.47    51.655 ...    1.24    -2.475  113.497]
 [   1.     160.937   68.768 ... -999.    -999.      46.226]
 [   1.    -999.     162.172 ... -999.    -999.      44.251]
 ...
 [   1.     105.457   60.526 ... -999.    -999.      41.992]
 [   1.      94.951   19.362 ... -999.    -999.       0.   ]
 [   1.    -999.      72.756 ... -999.    -999.       0.   ]]
[1. 1. 1. ... 1. 1. 1.]


## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)